export const danangSchoolWorkspaces = [
  {
    code: 'DHBK-DHDN',
    name: 'Trường Đại học Bách khoa - Đại học Đà Nẵng',
    shortName: 'DHBK',
    parentCode: 'UDN',
    isActive: true,
    registrationEnabled: true,
  },
  {
    code: 'DHKTE-DHDN',
    name: 'Trường Đại học Kinh tế - Đại học Đà Nẵng',
    shortName: 'DHKTE',
    parentCode: 'UDN',
    isActive: true,
    registrationEnabled: true,
  },
  {
    code: 'DHSP-DHDN',
    name: 'Trường Đại học Sư phạm - Đại học Đà Nẵng',
    shortName: 'DHSP',
    parentCode: 'UDN',
    isActive: true,
    registrationEnabled: true,
  },
  {
    code: 'DHNN-DHDN',
    name: 'Trường Đại học Ngoại ngữ - Đại học Đà Nẵng',
    shortName: 'DHNN',
    parentCode: 'UDN',
    isActive: true,
    registrationEnabled: true,
  },
  {
    code: 'DHSPKT-DHDN',
    name: 'Trường Đại học Sư phạm Kỹ thuật - Đại học Đà Nẵng',
    shortName: 'DHSPKT',
    parentCode: 'UDN',
    isActive: true,
    registrationEnabled: true,
  },
  {
    code: 'VKU-DHDN',
    name: 'Trường Đại học CNTT và Truyền thông Việt - Hàn - Đại học Đà Nẵng',
    shortName: 'VKU',
    parentCode: 'UDN',
    isActive: true,
    registrationEnabled: true,
  },
  {
    code: 'TYD-DHDN',
    name: 'Trường Y Dược - Đại học Đà Nẵng',
    shortName: 'TYD',
    parentCode: 'UDN',
    isActive: true,
    registrationEnabled: true,
  },
  {
    code: 'DTU-DN',
    name: 'Đại học Duy Tân',
    shortName: 'Duy Tân',
    parentCode: null,
    isActive: true,
    registrationEnabled: true,
  },
  {
    code: 'UDA-DN',
    name: 'Đại học Đông Á',
    shortName: 'Đông Á',
    parentCode: null,
    isActive: true,
    registrationEnabled: true,
  },
  {
    code: 'DAU-DN',
    name: 'Trường Đại học Kiến trúc Đà Nẵng',
    shortName: 'ĐH Kiến trúc ĐN',
    parentCode: null,
    isActive: true,
    registrationEnabled: true,
  },
  {
    code: 'TDTT-DN',
    name: 'Trường Đại học Thể dục Thể thao Đà Nẵng',
    shortName: 'ĐH TDTT ĐN',
    parentCode: null,
    isActive: true,
    registrationEnabled: true,
  },
  {
    code: 'DUMTP-DN',
    name: 'Trường Đại học Kỹ thuật Y - Dược Đà Nẵng',
    shortName: 'ĐH Kỹ thuật Y Dược ĐN',
    parentCode: null,
    isActive: true,
    registrationEnabled: true,
  },
  {
    code: 'QNU-DN',
    name: 'Trường Đại học Quảng Nam',
    shortName: 'ĐH Quảng Nam',
    parentCode: null,
    isActive: true,
    registrationEnabled: true,
  },
] as const;
