import { Criterion, MetricType } from '@prisma/client';
import type { CriteriaRuleConfig } from './rules.types';

export const schoolRules: CriteriaRuleConfig[] = [
  {
    criterion: Criterion.ethics,
    ruleKey: 'school_ethics_conduct_score',
    ruleType: 'metric_threshold',
    thresholdJson: { metric: MetricType.conduct_score, operator: '>=', value: 82 },
    evidenceRequirementsJson: {
      requirementGroups: [
        {
          key: 'ethics_foundation',
          title: 'Dữ liệu nền về đạo đức',
          operator: 'all_of',
          optional: false,
          requirements: [
            {
              key: 'conduct_score',
              title: 'Điểm rèn luyện',
              type: 'metric',
              metricType: MetricType.conduct_score,
              threshold: 82,
              operator: '>=',
              acceptedSources: ['system_data', 'manual_metric', 'manual_evidence'],
              formSchema: {
                fields: ['value', 'scale', 'schoolYear', 'sourceType'],
              },
              nextAction: {
                type: 'enter_or_link_metric',
                label: 'Nhập hoặc liên kết điểm rèn luyện',
              },
            },
            {
              key: 'no_violation',
              title: 'Không vi phạm pháp luật, quy chế và nội quy',
              type: 'system_confirmation',
              acceptedSources: ['system_data', 'manual_evidence'],
              nextAction: {
                type: 'wait_system_confirmation',
                label: 'Chờ nhà trường xác nhận tình trạng vi phạm',
              },
            },
          ],
        },
        {
          key: 'ethics_additional_achievements',
          title: 'Thành tích đạo đức bổ sung',
          operator: 'one_of',
          optional: true,
          requirements: [
            {
              key: 'political_theory_competition',
              title: 'Thi tìm hiểu lý luận chính trị',
              type: 'evidence',
              optional: true,
              criterion: Criterion.ethics,
              evidenceType: 'political_theory_competition',
              acceptedSources: ['manual_evidence', 'official_event'],
            },
            {
              key: 'exemplary_youth',
              title: 'Thanh niên tiên tiến/làm theo lời Bác',
              type: 'evidence',
              optional: true,
              criterion: Criterion.ethics,
              evidenceType: 'exemplary_youth',
              acceptedSources: ['manual_evidence', 'official_event'],
            },
            {
              key: 'good_person_good_deed',
              title: 'Gương người tốt việc tốt',
              type: 'evidence',
              optional: true,
              criterion: Criterion.ethics,
              evidenceType: 'good_person_good_deed',
              acceptedSources: ['manual_evidence', 'official_event'],
            },
            {
              key: 'recognized_courageous_action',
              title: 'Hành động dũng cảm được ghi nhận',
              type: 'evidence',
              optional: true,
              criterion: Criterion.ethics,
              evidenceType: 'recognized_courageous_action',
              acceptedSources: ['manual_evidence', 'official_event'],
            },
            {
              key: 'other_ethics_achievement',
              title: 'Thành tích đạo đức khác',
              type: 'evidence',
              optional: true,
              criterion: Criterion.ethics,
              evidenceType: 'other_ethics_achievement',
              acceptedSources: ['manual_evidence', 'official_event'],
            },
          ],
        },
      ],
    },
    humanReadableText: 'Cấp trường: điểm rèn luyện từ 82 trở lên.',
  },
  {
    criterion: Criterion.ethics,
    ruleKey: 'school_ethics_no_violation_review',
    ruleType: 'human_review_note',
    thresholdJson: null,
    evidenceRequirementsJson: { warningCode: 'NO_VIOLATION_NEEDS_REVIEW' },
    humanReadableText: 'Cấp trường: cần cán bộ xác nhận không vi phạm kỷ luật.',
  },
  {
    criterion: Criterion.academic,
    ruleKey: 'school_academic_gpa',
    ruleType: 'metric_threshold',
    thresholdJson: { metric: MetricType.gpa, operator: '>=', value: 3.0 },
    evidenceRequirementsJson: {
      requirementGroups: [
        {
          key: 'academic_foundation',
          title: 'Káº¿t quáº£ há»c táº­p',
          operator: 'all_of',
          optional: false,
          requirements: [
            {
              key: 'academic_gpa',
              title: 'GPA/ÄTB',
              type: 'metric',
              metricType: MetricType.gpa,
              threshold: 3.0,
              operator: '>=',
              acceptedSources: ['system_data', 'manual_metric', 'manual_evidence'],
              formSchema: {
                fields: ['value', 'scale', 'schoolYear', 'sourceType'],
                supportedScales: [4, 10],
              },
              nextAction: {
                type: 'enter_gpa',
                label: 'Nháº­p GPA vÃ  chá»n thang Ä‘iá»ƒm',
              },
            },
            {
              key: 'no_f_grade',
              title: 'KhÃ´ng cÃ³ há»c pháº§n Ä‘iá»ƒm F',
              type: 'system_confirmation',
              acceptedSources: ['system_data', 'manual_evidence'],
              nextAction: {
                type: 'confirm_no_f_grade',
                label: 'XÃ¡c nháº­n tÃ¬nh tráº¡ng Ä‘iá»ƒm F',
              },
            },
            {
              key: 'academic_period_valid',
              title: 'Dá»¯ liá»‡u thuá»™c Ä‘Ãºng nÄƒm há»c xÃ©t',
              type: 'system_confirmation',
              acceptedSources: ['system_data', 'manual_evidence'],
              nextAction: {
                type: 'upload_transcript_for_period',
                label: 'Táº£i báº£ng Ä‘iá»ƒm Ä‘á»ƒ xÃ¡c minh GPA',
              },
            },
          ],
        },
        {
          key: 'academic_additional_achievement',
          title: 'ThÃ nh tÃ­ch há»c thuáº­t bá»• sung',
          operator: 'one_of',
          optional: true,
          formSchema: {
            evidenceTypes: [
              'student_research',
              'academic_competition',
              'journal_article',
              'conference_paper',
              'thesis_or_capstone',
              'innovation_product',
              'academic_team',
              'academic_award',
              'other_academic_achievement',
            ],
            additionalAchievementRequired: false,
          },
          requirements: [
            'student_research',
            'academic_competition',
            'journal_article',
            'conference_paper',
            'thesis_or_capstone',
            'innovation_product',
            'academic_team',
            'academic_award',
            'other_academic_achievement',
          ].map((evidenceType) => ({
            key: evidenceType,
            title: evidenceType,
            type: 'evidence',
            optional: true,
            criterion: Criterion.academic,
            evidenceType,
            acceptedSources: ['manual_evidence', 'official_event'],
          })),
        },
      ],
    },
    humanReadableText: 'Cấp trường: GPA từ 3.0/4.0 trở lên.',
  },
  {
    criterion: Criterion.academic,
    ruleKey: 'school_academic_no_f_review',
    ruleType: 'human_review_note',
    thresholdJson: null,
    evidenceRequirementsJson: { warningCode: 'NO_F_GRADE_NEEDS_REVIEW' },
    humanReadableText: 'Cấp trường: cần cán bộ xác nhận không có học phần điểm F.',
  },
  {
    criterion: Criterion.physical,
    ruleKey: 'school_physical_evidence_or_score',
    ruleType: 'evidence_or_metric',
    thresholdJson: { metric: MetricType.physical_score, operator: '>=', value: 6.5 },
    evidenceRequirementsJson: { criterion: Criterion.physical },
    humanReadableText: 'Cấp trường: có minh chứng thể lực hoặc điểm thể lực từ 6.5.',
  },
  {
    criterion: Criterion.volunteer,
    ruleKey: 'school_volunteer_days_or_evidence',
    ruleType: 'evidence_or_metric',
    thresholdJson: { metric: MetricType.volunteer_days, operator: '>=', value: 2 },
    evidenceRequirementsJson: { criterion: Criterion.volunteer, convertedUnit: 'days' },
    humanReadableText: 'Cấp trường: có ít nhất 2 ngày tình nguyện hoặc minh chứng/sự kiện hợp lệ.',
  },
  {
    criterion: Criterion.integration,
    ruleKey: 'school_integration_evidence_or_language',
    ruleType: 'evidence_or_metric',
    thresholdJson: { metric: MetricType.foreign_language_score, operator: '>=', value: 2 },
    evidenceRequirementsJson: { criterion: Criterion.integration },
    humanReadableText: 'Cấp trường: có minh chứng hội nhập hoặc dữ liệu ngoại ngữ tương đương A2.',
  },
  {
    criterion: Criterion.priority,
    ruleKey: 'school_priority_optional',
    ruleType: 'human_review_note',
    thresholdJson: null,
    evidenceRequirementsJson: { optional: true, warningCode: 'PRIORITY_OPTIONAL' },
    humanReadableText: 'Tiêu chí ưu tiên là thông tin bổ sung, không bắt buộc ở MVP.',
  },
];
