import { Criterion, Level } from '@prisma/client';
import {
  activity,
  all,
  anyOf,
  award,
  bloodDonation,
  booleanRequirement,
  certificate,
  evidenceCategory,
  language,
  manualReview,
  noViolation,
  officialRecommendation,
  prerequisiteTitle,
  rule,
  threshold,
} from './criteria.helpers';
import type { SeedCriteriaConfig, SeedCriteriaRule } from './criteria.types';

const schoolSource = {
  sourceDocumentName: 'Tiêu chuẩn xét chọn danh hiệu Sinh viên 5 tốt cấp Trường - Trường Đại học Bách khoa, Đại học Đà Nẵng',
  sourceDocumentNumber: null,
  sourceIssuedAt: null,
  sourcePeriodLabel: 'Bộ tiêu chí hiện hành cấp Trường',
  sourceOrganization: 'Hội Sinh viên Trường Đại học Bách khoa - Đại học Đà Nẵng',
  sourceFileName: 'TieuchuanxetchonSV5totcapTruong-ĐHBK-ĐHĐN (1).pdf',
} as const;

const universitySource = {
  sourceDocumentName: 'Quy định tiêu chuẩn xét chọn Sinh viên 5 tốt cấp Đại học Đà Nẵng',
  sourceDocumentNumber: 'HSV-12-QĐ',
  sourceIssuedAt: null,
  sourcePeriodLabel: 'Bộ tiêu chí hiện hành cấp Đại học Đà Nẵng',
  sourceOrganization: 'Hội Sinh viên Đại học Đà Nẵng',
  sourceFileName: 'HSV-12-QĐ-Quy dinh tieu chuan SV5T cap DHDN (2).pdf',
} as const;

const citySource = {
  sourceDocumentName: 'Tiêu chuẩn xét chọn Sinh viên 5 tốt cấp Thành phố Đà Nẵng',
  sourceDocumentNumber: null,
  sourceIssuedAt: null,
  sourcePeriodLabel: 'Tiêu chuẩn cấp Thành phố Đà Nẵng năm 2022',
  sourceOrganization: 'Hội Sinh viên Việt Nam thành phố Đà Nẵng',
  sourceFileName: 'Tieu chuan xet sinh vien 5 tot cap Thanh Pho Da Nang 2022 (2).pdf',
} as const;

const centralSource = {
  sourceDocumentName:
    'Quy định về tiêu chuẩn xét chọn danh hiệu “Sinh viên 5 tốt” và “Tập thể sinh viên 5 tốt” cấp Trung ương giai đoạn 2019–2023 (sửa đổi, bổ sung)',
  sourceDocumentNumber: '201-QĐ/TWHSV',
  sourceIssuedAt: '2022-03-02',
  sourcePeriodLabel: 'Giai đoạn 2019–2023, sửa đổi bổ sung năm 2022',
  sourceOrganization: 'Ban Thư ký Trung ương Hội Sinh viên Việt Nam',
  sourceFileName: '1. Quy dinh tieu chuan xet chon Sinh vien 5 tot Final - scan (2).pdf',
} as const;

function withSource(
  sourceSection: string,
  sourceQuote: string,
  sourcePage: number | null = null,
): Pick<SeedCriteriaRule, 'sourcePage' | 'sourceSection' | 'sourceQuote'> {
  return { sourcePage, sourceSection, sourceQuote };
}

export const currentCriteriaSeedConfigs: SeedCriteriaConfig[] = [
  {
    code: 'DUT_SCHOOL_CURRENT',
    scope: Level.school,
    workspaceCode: 'DHBK-DHDN',
    title: 'Bộ tiêu chí Sinh viên 5 tốt cấp Trường ĐH Bách khoa',
    description: 'Cấu hình hiện hành cho Trường Đại học Bách khoa - Đại học Đà Nẵng.',
    ...schoolSource,
    rules: [
      rule({
        criterion: Criterion.ethics,
        ruleKey: 'ethics.conduct_score_82_and_no_violation',
        title: 'Điểm rèn luyện và không vi phạm',
        requirement: all([threshold('conduct_score', 82, { scale: 100 }), noViolation()]),
        mandatory: true,
        studentFriendlyText: 'Cần điểm rèn luyện từ 82/100 trở lên và không có vi phạm.',
        missingActionHints: ['Nhập hoặc liên kết điểm rèn luyện', 'Xác nhận không vi phạm'],
        sortOrder: 10,
        ...withSource('Đạo đức tốt', 'conduct score >= 82/100; no violation.'),
      }),
      rule({
        criterion: Criterion.academic,
        ruleKey: 'academic.gpa_3_no_f',
        title: 'GPA tối thiểu và không có điểm F',
        requirement: all([
          threshold('gpa', 3, { scale: 4 }),
          booleanRequirement('academic.no_f_grade', 'Không có học phần điểm F'),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần GPA từ 3.0/4.0 trở lên và không có học phần điểm F.',
        missingActionHints: ['Nhập GPA', 'Xác nhận không có điểm F'],
        sortOrder: 20,
        ...withSource('Học tập tốt', 'GPA >= 3.0/4.0; no F grade.'),
      }),
      rule({
        criterion: Criterion.physical,
        ruleKey: 'physical.any_one_branch',
        title: 'Một nhánh thể lực phù hợp',
        requirement: anyOf([
          evidenceCategory('physical_course_good', 'Kết quả giáo dục thể chất loại Khá trở lên'),
          activity('sport_activity', 'Tham gia hoạt động thể thao từ Liên chi đoàn/CLB/đội/nhóm trở lên'),
          activity('online_sport_activity', 'Tham gia hoạt động thể thao trực tuyến có xác nhận'),
          activity('sport_competition', 'Tham gia giải thể thao cấp Đại học Đà Nẵng, toàn quốc hoặc quốc tế'),
          activity('regular_sport_training', 'Tập luyện thường xuyên trong một câu lạc bộ, đội hoặc nhóm thể thao'),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần đáp ứng ít nhất một nhánh thể lực được quy định.',
        missingActionHints: ['Chọn cách chứng minh Thể lực tốt', 'Bổ sung minh chứng thể thao'],
        sortOrder: 30,
        ...withSource('Thể lực tốt', 'ANY, minimum 1, of the listed physical branches.'),
      }),
      rule({
        criterion: Criterion.volunteer,
        ruleKey: 'volunteer.any_campaign_days_blood_award_activities',
        title: 'Một nhánh tình nguyện phù hợp',
        requirement: anyOf([
          activity('recognized_volunteer_campaign', 'Hoàn thành một chiến dịch tình nguyện được công nhận'),
          activity('volunteer_days', 'Tham gia hoạt động tình nguyện có xác nhận ít nhất 2 ngày', {
            minimumDays: 2,
          }),
          bloodDonation('Hiến máu; mỗi lần quy đổi tương đương 1 ngày tình nguyện', 2, 1),
          award('volunteer_award', 'Có khen thưởng tình nguyện từ cấp Trường trở lên', Level.school),
          activity('youth_union_student_association_activity', 'Tham gia ít nhất 3 hoạt động Đoàn/Hội', {
            minimumCount: 3,
          }),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần đáp ứng ít nhất một nhánh Tình nguyện tốt; không bắt buộc đủ tất cả các nhánh.',
        missingActionHints: ['Bổ sung ngày tình nguyện hoặc minh chứng chiến dịch/khen thưởng'],
        sortOrder: 40,
        ...withSource('Tình nguyện tốt', 'ANY, minimum 1; do not incorrectly require all five volunteer branches.'),
      }),
      rule({
        criterion: Criterion.integration,
        ruleKey: 'integration.any_one_branch',
        title: 'Một nhánh hội nhập phù hợp',
        requirement: anyOf([
          certificate('officer_training', 'Tập huấn cán bộ Đoàn/Hội về kỹ năng mềm hoặc ngoại ngữ'),
          certificate('international_exchange', 'Chứng nhận hoạt động giao lưu quốc tế từ cấp Trường trở lên', Level.school),
          language('Ngoại ngữ A2 hoặc tương đương cho sinh viên năm 1-2', {
            minimumLevel: 'A2',
            studentYears: [1, 2],
          }),
          language('Ngoại ngữ B1 hoặc tương đương cho sinh viên năm 3-5', {
            minimumLevel: 'B1',
            studentYears: [3, 4, 5],
          }),
          award('foreign_language_competition', 'Đạt giải cuộc thi ngoại ngữ từ Liên chi đoàn/CLB/đội/nhóm trở lên'),
          certificate('english_competition', 'Chứng nhận cuộc thi tiếng Anh do Đoàn/Hội trường hoặc cấp cao hơn tổ chức'),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần đáp ứng ít nhất một nhánh Hội nhập tốt, trong đó ngưỡng ngoại ngữ phụ thuộc năm học.',
        missingActionHints: ['Bổ sung chứng chỉ ngoại ngữ hoặc minh chứng hoạt động hội nhập'],
        sortOrder: 50,
        ...withSource('Hội nhập tốt', 'A2 for years 1–2; B1 for years 3–5, or another listed branch.'),
      }),
      rule({
        criterion: Criterion.academic,
        ruleKey: 'priority.academic_research',
        title: 'Ưu tiên nghiên cứu học thuật',
        requirement: evidenceCategory('academic_research', 'Có tham gia nghiên cứu học thuật'),
        mandatory: false,
        priorityRule: true,
        studentFriendlyText: 'Thành tích nghiên cứu học thuật là tiêu chí ưu tiên, không thay thế GPA và điều kiện không có điểm F.',
        sortOrder: 90,
        ...withSource('Tiêu chí ưu tiên', 'Academic research participation is a priority condition.'),
      }),
    ],
  },
  {
    code: 'UDN_UNIVERSITY_CURRENT',
    scope: Level.university,
    workspaceCode: 'DHBK-DHDN',
    title: 'Bộ tiêu chí Sinh viên 5 tốt cấp Đại học Đà Nẵng',
    description: 'Cấu hình hiện hành cho cấp Đại học Đà Nẵng.',
    ...universitySource,
    rules: [
      rule({
        criterion: Criterion.ethics,
        ruleKey: 'prerequisite.school_title_and_recommendation',
        title: 'Điều kiện nền cấp Đại học Đà Nẵng',
        requirement: all([
          booleanRequirement('student.currently_studying_udn_member', 'Đang học tại cơ sở thành viên/đơn vị thuộc Đại học Đà Nẵng'),
          prerequisiteTitle(Level.school, 'Đã đạt danh hiệu Sinh viên 5 tốt cấp Trường'),
          officialRecommendation('Được Hội Sinh viên hoặc Đoàn Thanh niên cấp Trường giới thiệu chính thức'),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cấp Đại học Đà Nẵng yêu cầu đang học tại đơn vị thuộc ĐHĐN, đã đạt cấp Trường và có giới thiệu chính thức.',
        sortOrder: 5,
        ...withSource('Điều kiện chung', 'School-level achieved and official recommendation are mandatory.'),
      }),
      rule({
        criterion: Criterion.ethics,
        ruleKey: 'ethics.conduct_score_80_and_no_violation',
        title: 'Đạo đức cấp Đại học Đà Nẵng',
        requirement: all([threshold('conduct_score', 80, { scale: 100 }), noViolation()]),
        mandatory: true,
        studentFriendlyText: 'Cần điểm rèn luyện từ 80/100 trở lên và không có vi phạm.',
        sortOrder: 10,
        ...withSource('Đạo đức tốt', 'conduct score >= 80/100; no violation.'),
      }),
      rule({
        criterion: Criterion.academic,
        ruleKey: 'academic.gpa_3_2_and_achievement',
        title: 'GPA và thành tích học thuật bổ sung',
        requirement: all([
          threshold('gpa', 3.2, { scale: 4 }),
          anyOf([
            evidenceCategory('student_research_faculty', 'Nghiên cứu khoa học từ cấp Khoa trở lên'),
            evidenceCategory('graduation_project_score_8', 'Điểm đồ án/khóa luận tốt nghiệp từ 8.0'),
            evidenceCategory('specialist_journal_article', 'Bài báo trên tạp chí chuyên ngành'),
            evidenceCategory('specialist_conference_paper', 'Báo cáo hội nghị chuyên ngành từ cấp Khoa trở lên'),
            award('patent_publication_or_award', 'Bằng sáng chế/công bố/giải thưởng từ cấp Trường trở lên', Level.school),
            activity('academic_competition_team', 'Thành viên đội tuyển học thuật từ cấp Trường trở lên'),
            award('research_startup_innovation_award', 'Giải thưởng nghiên cứu, khởi nghiệp hoặc đổi mới sáng tạo từ cấp Trường trở lên', Level.school),
          ]),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần GPA từ 3.2/4.0 trở lên và ít nhất một thành tích học thuật bổ sung.',
        sortOrder: 20,
        ...withSource('Học tập tốt', 'GPA >= 3.2/4.0 and ANY one academic achievement.'),
      }),
      rule({
        criterion: Criterion.physical,
        ruleKey: 'physical.any_one_branch',
        title: 'Thể lực cấp Đại học Đà Nẵng',
        requirement: anyOf([
          certificate('healthy_youth_student', 'Danh hiệu Thanh niên khỏe hoặc Sinh viên khỏe'),
          activity('regular_sport_training', 'Tập luyện thể thao thường xuyên trong CLB/đội/nhóm'),
          activity('sport_competition', 'Tham gia đội tuyển hoặc thi đấu thể thao'),
          evidenceCategory('physical_course_good', 'Kết quả giáo dục thể chất hằng năm loại Khá trở lên'),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần đáp ứng ít nhất một nhánh Thể lực tốt cấp Đại học Đà Nẵng.',
        sortOrder: 30,
        ...withSource('Thể lực tốt', 'ANY, minimum 1, of the listed physical branches.'),
      }),
      rule({
        criterion: Criterion.volunteer,
        ruleKey: 'volunteer.any_campaign_3_days_award',
        title: 'Tình nguyện cấp Đại học Đà Nẵng',
        requirement: anyOf([
          certificate('recognized_volunteer_campaign', 'Chứng nhận một chiến dịch tình nguyện được công nhận'),
          activity('volunteer_days', 'Tích lũy ít nhất 3 ngày tình nguyện', { minimumDays: 3 }),
          award('volunteer_award', 'Khen thưởng tình nguyện từ cấp Trường trở lên', Level.school),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần một trong các nhánh tình nguyện: chiến dịch, ít nhất 3 ngày, hoặc khen thưởng phù hợp.',
        sortOrder: 40,
        ...withSource('Tình nguyện tốt', 'ANY: recognized campaign, 3 accumulated days, or volunteer award.'),
      }),
      rule({
        criterion: Criterion.integration,
        ruleKey: 'integration.base_activity_and_language_or_exchange',
        title: 'Hội nhập cấp Đại học Đà Nẵng',
        requirement: all([
          anyOf([
            certificate('social_practice_skill_course', 'Hoàn thành một khóa kỹ năng thực hành xã hội'),
            award('youth_union_student_association_commendation', 'Khen thưởng Đoàn/Hội từ cấp Trường trở lên', Level.school),
          ]),
          activity('integration_activity', 'Tham gia ít nhất một hoạt động hội nhập từ cấp Khoa trở lên', {
            minimumCount: 1,
          }),
          anyOf([
            language('B1 hoặc tương đương', { minimumLevel: 'B1' }),
            language('Điểm trung bình ngoại ngữ tích lũy từ 3.0/4.0', { minimumScore: 3, scale: 4 }),
            certificate('international_exchange', 'Ít nhất một hoạt động giao lưu quốc tế'),
            award('knowledge_or_language_competition', 'Giải ba trở lên cuộc thi kiến thức hoặc ngoại ngữ từ cấp Khoa trở lên', Level.university),
          ]),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần điều kiện nền, một hoạt động hội nhập và một nhánh ngoại ngữ/giao lưu/giải thưởng phù hợp.',
        sortOrder: 50,
        ...withSource('Hội nhập tốt', 'Base course or commendation; integration activity; and ANY language/exchange/competition branch.'),
      }),
      rule({
        criterion: Criterion.academic,
        ruleKey: 'priority.full_priority_list_reference',
        title: 'Danh sách ưu tiên cấp Đại học Đà Nẵng',
        requirement: manualReview('udn_priority_list', 'Danh sách ưu tiên đầy đủ cần đối chiếu cán bộ khi dùng để xếp thứ tự'),
        mandatory: false,
        priorityRule: true,
        studentFriendlyText: 'Các tiêu chí ưu tiên chỉ hỗ trợ xếp thứ tự, không thay thế điều kiện bắt buộc.',
        sortOrder: 90,
        ...withSource('Tiêu chí ưu tiên', 'Seed the full priority list separately with priorityRule=true.'),
      }),
    ],
  },
  {
    code: 'DANANG_CITY_CURRENT',
    scope: Level.city,
    workspaceCode: null,
    title: 'Bộ tiêu chí Sinh viên 5 tốt cấp Thành phố Đà Nẵng',
    description: 'Cấu hình hiện hành cho cấp Thành phố Đà Nẵng.',
    ...citySource,
    rules: [
      rule({
        criterion: Criterion.ethics,
        ruleKey: 'prerequisite.school_title_and_selection_council_recommendation',
        title: 'Điều kiện nền cấp Thành phố',
        requirement: all([
          prerequisiteTitle(Level.school, 'Đã đạt danh hiệu Sinh viên 5 tốt cấp Trường'),
          officialRecommendation('Được Hội đồng xét chọn cấp Trường giới thiệu chính thức'),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cấp Thành phố yêu cầu đã đạt cấp Trường và có giới thiệu chính thức từ Hội đồng cấp Trường.',
        sortOrder: 5,
        ...withSource('Điều kiện chung', 'School-level title and official recommendation are mandatory.'),
      }),
      rule({
        criterion: Criterion.ethics,
        ruleKey: 'ethics.conduct_80_no_violation_and_extra',
        title: 'Đạo đức cấp Thành phố',
        requirement: all([
          anyOf([
            threshold('conduct_score', 80, { scale: 100 }),
            booleanRequirement('ethics.good_equivalent_classification', 'Xếp loại rèn luyện tương đương Giỏi'),
          ]),
          noViolation(),
          anyOf([
            evidenceCategory('communist_party_member', 'Đảng viên Đảng Cộng sản Việt Nam'),
            activity('ideology_contest_team', 'Thành viên đội thi Mác-Lênin/Tư tưởng Hồ Chí Minh từ chi đoàn trở lên'),
            evidenceCategory('ideology_article_or_presentation', 'Bài viết/tham luận lĩnh vực tư tưởng phù hợp'),
            award('exemplary_youth_good_deed_brave_action', 'Gương thanh niên tiêu biểu, người tốt việc tốt hoặc hành động dũng cảm'),
          ]),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần điểm/xếp loại rèn luyện phù hợp, không vi phạm và một thành tích đạo đức bổ sung.',
        sortOrder: 10,
        ...withSource('Đạo đức tốt', 'Conduct threshold, no violation, and ANY one additional ethics achievement.'),
      }),
      rule({
        criterion: Criterion.academic,
        ruleKey: 'academic.gpa_by_program_and_achievement',
        title: 'Học tập cấp Thành phố',
        requirement: all([
          anyOf([
            threshold('gpa', 3.2, { scale: 4, label: 'Sinh viên đại học GPA từ 3.2/4.0' }),
            threshold('gpa', 8, { scale: 10, label: 'Sinh viên đại học GPA từ 8.0/10' }),
            threshold('gpa', 3, { scale: 4, label: 'Sinh viên cao đẳng GPA từ 3.0/4.0' }),
            threshold('gpa', 7.5, { scale: 10, label: 'Sinh viên cao đẳng GPA từ 7.5/10' }),
          ]),
          evidenceCategory('academic_achievement', 'Ít nhất một thành tích học thuật được quy định'),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần đạt ngưỡng GPA theo hệ đào tạo và có ít nhất một thành tích học thuật bổ sung.',
        sortOrder: 20,
        ...withSource('Học tập tốt', 'University and college GPA alternatives plus ANY listed academic achievement.'),
      }),
      rule({
        criterion: Criterion.physical,
        ruleKey: 'physical.any_one_city_branch',
        title: 'Thể lực cấp Thành phố',
        requirement: anyOf([
          certificate('healthy_youth_school', 'Thanh niên khỏe từ cấp Trường trở lên', Level.school),
          award('sports_activity_faculty', 'Tham gia và đạt giải hoạt động thể thao từ cấp Khoa trở lên', Level.university),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần ít nhất một minh chứng thể lực phù hợp cấp Thành phố.',
        sortOrder: 30,
        ...withSource('Thể lực tốt', 'ANY one physical branch.'),
      }),
      rule({
        criterion: Criterion.volunteer,
        ruleKey: 'volunteer.five_days_and_commendation',
        title: 'Tình nguyện cấp Thành phố',
        requirement: all([
          activity('volunteer_days', 'Ít nhất 5 ngày tình nguyện tích lũy', { minimumDays: 5 }),
          award('volunteer_commendation', 'Khen thưởng tình nguyện từ cấp Khoa trở lên', Level.university),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần đồng thời ít nhất 5 ngày tình nguyện và khen thưởng tình nguyện phù hợp.',
        sortOrder: 40,
        ...withSource('Tình nguyện tốt', 'Volunteer requires both five days and qualifying commendation.'),
      }),
      rule({
        criterion: Criterion.integration,
        ruleKey: 'integration.city_base_and_one_branch',
        title: 'Hội nhập cấp Thành phố',
        requirement: all([
          anyOf([
            certificate('social_practice_skill_course', 'Hoàn thành một khóa kỹ năng thực hành xã hội'),
            award('youth_union_student_association_commendation', 'Khen thưởng Đoàn/Hội từ cấp Khoa trở lên', Level.university),
          ]),
          anyOf([
            language('B1/C hoặc tương đương', { minimumLevel: 'B1' }),
            language('TOEIC từ 405', { minimumScore: 405 }),
            language('TOEFL iBT từ 53', { minimumScore: 53 }),
            language('IELTS từ 4.5', { minimumScore: 4.5 }),
            language('Điểm trung bình ngoại ngữ từ 3.0/4.0', { minimumScore: 3, scale: 4 }),
            language('Điểm trung bình ngoại ngữ từ 7.5/10', { minimumScore: 7.5, scale: 10 }),
            certificate('international_exchange_or_integration', 'Hoạt động giao lưu quốc tế hoặc hội nhập từ cấp Khoa trở lên'),
            award('knowledge_or_language_competition', 'Giải ba trở lên cuộc thi kiến thức hoặc ngoại ngữ từ cấp Khoa trở lên', Level.university),
          ]),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần điều kiện nền và một nhánh ngoại ngữ/giao lưu/giải thưởng hội nhập phù hợp.',
        sortOrder: 50,
        ...withSource('Hội nhập tốt', 'Base condition and ANY language/exchange/competition branch.'),
      }),
      rule({
        criterion: Criterion.ethics,
        ruleKey: 'info.recognition_period',
        title: 'Thông tin giai đoạn xét chọn',
        requirement: manualReview('city_recognition_period', 'Thông tin thời gian công nhận cần cán bộ đối chiếu theo đợt xét chọn'),
        mandatory: false,
        priorityRule: true,
        studentFriendlyText: 'Mốc thời gian công nhận là thông tin nguồn; hệ thống không dùng nó để tạo version tiêu chí.',
        sortOrder: 90,
        ...withSource('Thông tin thời gian xét chọn', 'Preserve recognition-period statement as metadata or manual informational rule.'),
      }),
    ],
  },
  {
    code: 'CENTRAL_CURRENT',
    scope: Level.central,
    workspaceCode: null,
    title: 'Bộ tiêu chí Sinh viên 5 tốt cấp Trung ương',
    description: 'Cấu hình hiện hành cấp Trung ương theo quy định 201-QĐ/TWHSV.',
    ...centralSource,
    rules: [
      rule({
        criterion: Criterion.ethics,
        ruleKey: 'prerequisite.provincial_or_school_exception_and_recommendation',
        title: 'Điều kiện nền cấp Trung ương',
        requirement: all([
          anyOf([
            prerequisiteTitle(Level.city, 'Đã đạt danh hiệu cấp tỉnh/thành phố'),
            prerequisiteTitle(Level.school, 'Trường hợp cơ sở trực thuộc Trung ương: danh hiệu cấp Trường có thể đáp ứng điều kiện'),
          ]),
          officialRecommendation('Được tổ chức Hội Sinh viên hoặc Đoàn Thanh niên có thẩm quyền giới thiệu'),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cấp Trung ương cần danh hiệu cấp tỉnh/thành phố hoặc ngoại lệ cơ sở trực thuộc, kèm giới thiệu chính thức.',
        sortOrder: 5,
        ...withSource('Điều kiện chung', 'Provincial-level title or central-affiliated exception and official recommendation.'),
      }),
      rule({
        criterion: Criterion.ethics,
        ruleKey: 'ethics.conduct_90_no_violation_and_extra',
        title: 'Đạo đức cấp Trung ương',
        requirement: all([
          anyOf([
            threshold('conduct_score', 90, { scale: 100 }),
            booleanRequirement('ethics.highest_equivalent_classification', 'Xếp loại rèn luyện tương đương cao nhất tại cơ sở đặc thù'),
          ]),
          noViolation(),
          anyOf([
            activity('ideology_contest_team', 'Thành viên đội thi Mác-Lênin/Tư tưởng Hồ Chí Minh từ cấp Trường trở lên'),
            award('exemplary_youth_good_deed_rescue', 'Gương thanh niên tiêu biểu/người tốt việc tốt/hành động dũng cảm theo cấp được quy định'),
          ]),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần ngưỡng đạo đức cao hơn, không vi phạm và một thành tích đạo đức bổ sung.',
        sortOrder: 10,
        ...withSource('Đạo đức tốt', 'Conduct score >= 90/100, no violation, and ANY one additional ethics achievement.'),
      }),
      rule({
        criterion: Criterion.academic,
        ruleKey: 'academic.central_gpa_by_program_and_achievement',
        title: 'Học tập cấp Trung ương',
        requirement: all([
          anyOf([
            threshold('gpa', 3.4, { scale: 4, label: 'Đại học/học viện GPA từ 3.4/4.0' }),
            threshold('gpa', 8.5, { scale: 10, label: 'Đại học/học viện GPA từ 8.5/10' }),
            threshold('gpa', 3.2, { scale: 4, label: 'Cao đẳng GPA từ 3.2/4.0' }),
            threshold('gpa', 8, { scale: 10, label: 'Cao đẳng GPA từ 8.0/10' }),
          ]),
          evidenceCategory('academic_achievement', 'Ít nhất một thành tích học thuật trong mục 2.2'),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần đạt ngưỡng GPA cấp Trung ương và có thêm một thành tích học thuật phù hợp.',
        sortOrder: 20,
        ...withSource('Học tập tốt', 'University GPA >= 3.4/4.0 or 8.5/10; college GPA >= 3.2/4.0 or 8.0/10; plus achievement.'),
      }),
      rule({
        criterion: Criterion.physical,
        ruleKey: 'physical.central_any_branch_with_appendix_reference',
        title: 'Thể lực cấp Trung ương',
        requirement: anyOf([
          certificate('healthy_student_provincial', 'Đạt kiểm tra thể lực và danh hiệu Sinh viên khỏe từ cấp tỉnh/thành phố trở lên', Level.city),
          activity('central_sports', 'Tham gia thể thao cấp Trung ương'),
          award('mass_sports_school', 'Tham gia và đạt giải hoạt động thể thao quần chúng từ cấp Trường trở lên', Level.school),
          manualReview('central_physical_appendix', 'Phụ lục kiểm tra thể lực chi tiết cần cán bộ đối chiếu khi chưa đủ dữ liệu tự động', {
            containsGenderSpecificEvents: true,
            requiresSelectedEventCounts: true,
          }),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần đáp ứng một nhánh thể lực cấp Trung ương; phụ lục thể lực chi tiết có thể cần cán bộ xem trực tiếp.',
        sortOrder: 30,
        ...withSource('Thể lực tốt', 'Physical-fitness appendix is preserved as manual-review reference when full automatic evaluation is not supported.'),
      }),
      rule({
        criterion: Criterion.volunteer,
        ruleKey: 'volunteer.central_five_days_and_commendation',
        title: 'Tình nguyện cấp Trung ương',
        requirement: all([
          activity('volunteer_days', 'Ít nhất 5 ngày tình nguyện tích lũy', { minimumDays: 5 }),
          award('volunteer_commendation', 'Khen thưởng tình nguyện từ cấp tỉnh/thành phố hoặc UBND cấp huyện trở lên', Level.city),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần đồng thời ít nhất 5 ngày tình nguyện và khen thưởng tình nguyện đúng cấp.',
        sortOrder: 40,
        ...withSource('Tình nguyện tốt', 'Volunteer requires both five days and qualifying commendation.'),
      }),
      rule({
        criterion: Criterion.integration,
        ruleKey: 'integration.central_all_base_language_and_extra',
        title: 'Hội nhập cấp Trung ương',
        requirement: all([
          anyOf([
            certificate('social_practice_skill_course', 'Hoàn thành một khóa kỹ năng thực hành xã hội'),
            award('youth_union_student_association_commendation', 'Khen thưởng Đoàn/Hội từ cấp Trường trở lên', Level.school),
          ]),
          activity('integration_activity', 'Tham gia tích cực ít nhất một hoạt động hội nhập từ cấp Trường trở lên', {
            minimumCount: 1,
          }),
          anyOf([
            language('B1 hoặc tương đương', { minimumLevel: 'B1' }),
            language('Điểm trung bình ngoại ngữ từ 3.2/4.0', { minimumScore: 3.2, scale: 4 }),
            language('Điểm trung bình ngoại ngữ từ 8.0/10', { minimumScore: 8, scale: 10 }),
          ]),
          anyOf([
            certificate('international_exchange', 'Ít nhất một hoạt động giao lưu quốc tế'),
            award('integration_or_language_competition', 'Giải ba trở lên cuộc thi kiến thức hội nhập hoặc ngoại ngữ từ cấp Trường trở lên', Level.school),
          ]),
        ]),
        mandatory: true,
        studentFriendlyText: 'Cần điều kiện nền, hoạt động hội nhập, ngoại ngữ phù hợp và thêm một nhánh giao lưu/giải thưởng.',
        sortOrder: 50,
        ...withSource('Hội nhập tốt', 'Base, activity, language, and ANY exchange/competition branch are mandatory groups.'),
      }),
      rule({
        criterion: Criterion.ethics,
        ruleKey: 'info.recognition_time',
        title: 'Thông tin thời gian công nhận',
        requirement: manualReview('central_recognition_time', 'Thông tin thời gian công nhận cần cán bộ đối chiếu theo đợt xét chọn'),
        mandatory: false,
        priorityRule: true,
        studentFriendlyText: 'Mốc thời gian trong nguồn được lưu để tham chiếu, không tạo version tiêu chí.',
        sortOrder: 90,
        ...withSource('Thông tin thời gian xét chọn', 'Preserve recognition-time statement as metadata or informational rule.'),
      }),
    ],
  },
];
